name: Horizon
version: '${project.version}'
main: de.simplex.horizon.horizon.Horizon
load: STARTUP
api-version: 1.19

author: WillyButz
authors: [ ]
description: Ein Plugin für Horizon.
website: https://discord.gg/

commands:
